blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions & Questions
    url: https://github.com/Gaetano-Taormina/FuelFinder-Italy/discussions
    about: Ask questions or discuss ideas with the community.
